name: "Release"

on:
  release:
    types: [published]

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    timeout-minutes: 15

    permissions:
      contents: write
      packages: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: "Create App Token"
        id: app
        uses: actions/create-github-app-token@v2
        with:
          app-id: 146360
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: smashedr
          repositories: "bup,homebrew-test"

      # Note: app tokens can not write to packages
      - name: "Docker Login"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          #username: ${{ vars.GHCR_USER }}
          #password: ${{ secrets.GHCR_PASS }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Setup Buildx"
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: "Setup Go"
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: "GoReleaser"
        id: go
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6.4.0
        env:
          GITHUB_TOKEN: ${{ steps.app.outputs.token }}
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean

      - name: "Debug GoReleaser"
        continue-on-error: true
        env:
          artifacts: ${{ steps.go.outputs.artifacts }}
          metadata: ${{ steps.go.outputs.metadata }}
        run: |
          echo "artifacts: ${{ env.artifacts }}"
          echo "metadata: ${{ env.metadata }}"

      - name: "Upload i386 to Actions"
        uses: actions/upload-artifact@v6
        with:
          name: bup-i386
          path: dist/bup_windows_386_sse2/bup.exe

      - name: "Upload x86_64 to Actions"
        uses: actions/upload-artifact@v6
        with:
          name: bup-x86_64
          path: dist/bup_windows_amd64_v1/bup.exe

      #- name: "VirusTotal"
      #  uses: cssnr/virustotal-action@v1
      #  continue-on-error: true
      #  with:
      #    vt_api_key: ${{ secrets.VT_API_KEY }}
      #    rate_limit: 4
      #    update_release: true
      #    release_heading: "ðŸ›¡ï¸ **VirusTotal Results:**"
      #    summary: true
      #    collapsed: true

      - name: "Cleanup Release"
        if: ${{ failure() }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo -e "\n## Cleanup Release\n\n" >> "$GITHUB_STEP_SUMMARY"
          echo -e "Deleting Release and Tag: \`${{ github.ref_name }}\`\n\n" >> "$GITHUB_STEP_SUMMARY"
          if gh release delete "${{ github.ref_name }}" --cleanup-tag;then
            echo -e "âœ… Cleanup Success.\n" >> "$GITHUB_STEP_SUMMARY"
          else
            echo -e "â›” Cleanup Failed!\n" >> "$GITHUB_STEP_SUMMARY"
          fi

  windows:
    name: "Windows Installer"
    runs-on: windows-latest
    timeout-minutes: 15
    needs: [release]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Download i386 Artifact"
        uses: actions/download-artifact@v7
        with:
          name: bup-i386
          path: dist/i386

      - name: "Download x86_64 Artifact"
        uses: actions/download-artifact@v7
        with:
          name: bup-x86_64
          path: dist/x86_64

      - name: "Download PathMgr"
        uses: robinraju/release-downloader@v1.10
        with:
          repository: "Bill-Stewart/PathMgr"
          fileName: "PathMgr-2.0.0.zip"
          out-file-path: "dist/PathMgr"
          tag: "v2.0.0"
          extract: true

      - name: "Debug Artifacts"
        shell: bash
        run: |
          ls -lAhR dist

      - name: "Inno Setup"
        #shell: bash
        run: |
          echo "Building Version: ${{ github.ref_name }}"
          iscc.exe /DMyAppVersion=${{ github.ref_name }} installer.iss

      - name: "Debug Inno"
        shell: bash
        run: |
          ls -lAhR out

      - name: "Upload to Actions"
        uses: actions/upload-artifact@v6
        with:
          name: installer
          path: out

      - name: "Upload Release"
        if: ${{ github.event_name == 'release' }}
        uses: cssnr/upload-release-action@v1
        with:
          globs: out/*

  virustotal:
    name: "VirusTotal Scan"
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [windows]

    steps:
      - name: "VirusTotal"
        uses: cssnr/virustotal-action@master
        continue-on-error: true
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          collapsed: true
