name: "Release"

on:
  release:
    types: [published]

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: "Setup Go"
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: "Create App Token"
        id: app
        uses: actions/create-github-app-token@v2
        with:
          app-id: 146360
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: smashedr
          repositories: "bup,homebrew-test"

      - name: "Docker Login"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          # Note: app tokens can not create new packages
          username: ${{ github.repository_owner }}
          password: ${{ steps.app.outputs.token }}
          #username: ${{ vars.GHCR_USER }}
          #password: ${{ secrets.GHCR_PASS }}

      - name: "Setup Buildx"
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: "GoReleaser"
        id: go
        uses: goreleaser/goreleaser-action@v6
        env:
          GITHUB_TOKEN: ${{ steps.app.outputs.token }}
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean

      - name: "Debug"
        continue-on-error: true
        env:
          artifacts: ${{ steps.go.outputs.artifacts }}
          metadata: ${{ steps.go.outputs.metadata }}
        run: |
          echo "artifacts: ${{ env.artifacts }}"
          echo "metadata: ${{ env.metadata }}"
