name: "Release"

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: "Debug event.json"
        if: ${{ !github.event.act }}
        continue-on-error: true
        run: cat "${GITHUB_EVENT_PATH}"
      - name: "Debug CTX github"
        if: ${{ !github.event.act }}
        continue-on-error: true
        env:
          GITHUB_CTX: ${{ toJSON(github) }}
        run: echo "$GITHUB_CTX"
      - name: "Debug Environment"
        if: ${{ !github.event.act }}
        continue-on-error: true
        run: env

      # Note: app/workflow tokens can NOT write to packages with packages: write
      - name: "Docker Login"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ vars.GHCR_USER }}
          password: ${{ secrets.GHCR_PASS }}

      - name: "Setup Buildx"
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: "Setup Go"
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: "GoReleaser"
        id: go
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6.4.0
        env:
          #GITHUB_TOKEN: ${{ steps.app.outputs.token }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean

      - name: "Debug GoReleaser"
        continue-on-error: true
        env:
          artifacts: ${{ steps.go.outputs.artifacts }}
          metadata: ${{ steps.go.outputs.metadata }}
        run: |
          echo "artifacts: ${artifacts}"
          echo "metadata: ${metadata}"

      - name: "Upload i386 to Actions"
        uses: actions/upload-artifact@v6
        with:
          name: bup-i386
          path: dist/bup_windows_386_sse2/bup.exe

      - name: "Upload x86_64 to Actions"
        uses: actions/upload-artifact@v6
        with:
          name: bup-x86_64
          path: dist/bup_windows_amd64_v1/bup.exe

      - name: "Upload Formula to Actions"
        uses: actions/upload-artifact@v6
        with:
          name: bup-formula
          path: dist/homebrew/Formula/bup.rb

  windows:
    name: "Windows Installer"
    runs-on: windows-latest
    timeout-minutes: 15
    needs: [build]

    env:
      output: "out"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Download i386 Artifact"
        uses: actions/download-artifact@v7
        with:
          name: bup-i386
          path: dist/i386

      - name: "Download x86_64 Artifact"
        uses: actions/download-artifact@v7
        with:
          name: bup-x86_64
          path: dist/x86_64

      - name: "Download PathMgr"
        uses: robinraju/release-downloader@daf26c55d821e836577a15f77d86ddc078948b05 # v1.12
        with:
          repository: "Bill-Stewart/PathMgr"
          fileName: "PathMgr-2.0.0.zip"
          out-file-path: "dist/PathMgr"
          tag: "v2.0.0"
          extract: true

      - name: "Debug Artifacts"
        run: |
          ls dist

      - name: "Inno Setup"
        run: |
          echo "Building Version: ${{ github.ref_name }}"
          iscc.exe "/DMyAppVersion=${{ github.ref_name }}" installer.iss

      - name: "Debug Output"
        run: |
          ls "${{ env.output }}"

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v6
        with:
          name: installer
          path: ${{ env.output }}

      - name: "Upload Release"
        if: ${{ github.event_name == 'release' }}
        uses: cssnr/upload-release-action@v1
        with:
          globs: "${{ env.output }}/*"

  release:
    name: "Release"
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [windows]

    steps:
      - name: "Download Formula Artifact"
        if: ${{ !github.event.release.prerelease }}
        uses: actions/download-artifact@v7
        with:
          name: bup-formula
          path: dist/formula

      - name: "Debug Formula"
        if: ${{ !github.event.release.prerelease }}
        continue-on-error: true
        run: |
          ls -lAhR dist/formula

      - name: "Create App Token"
        if: ${{ !github.event.release.prerelease }}
        id: app
        uses: actions/create-github-app-token@v2
        with:
          app-id: 146360
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: cssnr
          repositories: "homebrew-tap"

      - name: "Homebrew Action"
        if: ${{ !github.event.release.prerelease }}
        uses: cssnr/homebrew-action@master
        with:
          file: dist/formula/bup.rb
          repo: cssnr/homebrew-tap
          token: ${{ steps.app.outputs.token }}

      - name: "VirusTotal"
        uses: cssnr/virustotal-action@master
        continue-on-error: true
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          collapsed: true

  check:
    name: "Check"
    if: ${{ always() }}
    runs-on: Ubuntu-latest
    timeout-minutes: 5
    needs: [release]

    steps:
      - name: "Alls Green"
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
          #allowed-failures: docs, linters
          #allowed-skips: non-voting-flaky-job

      - name: "Cleanup Release"
        if: ${{ failure() }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo -e "\n## Cleanup Release\n\n" >> "$GITHUB_STEP_SUMMARY"
          echo -e "Deleting Release and Tag: \`${{ github.ref_name }}\`\n\n" >> "$GITHUB_STEP_SUMMARY"
          if gh release delete "${{ github.ref_name }}" --cleanup-tag;then
            echo -e "✅ Cleanup Success.\n" >> "$GITHUB_STEP_SUMMARY"
          else
            echo -e "⛔ Cleanup Failed!\n" >> "$GITHUB_STEP_SUMMARY"
          fi
