name: "Release"

on:
  release:
    types: [published]

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    timeout-minutes: 15

    #permissions:
    #  contents: write
    #  packages: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: "Create App Token"
        id: app
        uses: actions/create-github-app-token@v2
        with:
          app-id: 146360
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: smashedr
          repositories: "bup,homebrew-test"

      # Note: app tokens can not write to packages
      - name: "Docker Login"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ vars.GHCR_USER }}
          password: ${{ secrets.GHCR_PASS }}

      - name: "Setup Buildx"
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: "Setup Go"
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: "GoReleaser"
        id: go
        uses: goreleaser/goreleaser-action@v6
        env:
          GITHUB_TOKEN: ${{ steps.app.outputs.token }}
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean

      - name: "Debug"
        continue-on-error: true
        env:
          artifacts: ${{ steps.go.outputs.artifacts }}
          metadata: ${{ steps.go.outputs.metadata }}
        run: |
          echo "artifacts: ${{ env.artifacts }}"
          echo "metadata: ${{ env.metadata }}"

      - name: "VirusTotal"
        uses: cssnr/virustotal-action@v1
        continue-on-error: true
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          rate_limit: 4
          update_release: true
          release_heading: "ðŸ›¡ï¸ **VirusTotal Results:**"
          summary: true
          collapsed: true

      - name: "Cleanup Release"
        if: ${{ failure() }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo -e "\n## Cleanup Release\n\n" >> "$GITHUB_STEP_SUMMARY"
          echo -e "Deleting Release and Tag: \`${{ github.ref_name }}\`\n\n" >> "$GITHUB_STEP_SUMMARY"
          if gh release delete "${{ github.ref_name }}" --cleanup-tag;then
            echo -e "âœ… Cleanup Success.\n" >> "$GITHUB_STEP_SUMMARY"
          else
            echo -e "â›” Cleanup Failed!\n" >> "$GITHUB_STEP_SUMMARY"
          fi
